name: Build and package Weather - Debugs

on: push

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      PYTHONVERSION: "3.11.1"
      MACOSX_DEPLOYMENT_TARGET: "13.6"
      PYI_BUILD_MODE: "onedir"

    steps:
      - uses: actions/checkout@v2

      - name: Uninstall homebrew
        run: |
          curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          chmod +x ./uninstall.sh
          sudo ./uninstall.sh --force
          sudo rm -rf /usr/local/Homebrew
          sudo rm -rf /usr/local/Caskroom
          sudo rm -rf /usr/local/bin/brew

      - name: Cache Python download
        id: cache-python-download
        uses: actions/cache@v3
        with:
          path: ~/python.pkg
          key: macOS-Python-${{ env.PYTHON_VERSION }}

      - name: Get Python
        run: |
          curl https://www.python.org/ftp/python/${PYTHONVERSION}/python-${PYTHONVERSION}-macos11.pkg -o ~/python.pkg
      - name: Install Python
        run: sudo installer -pkg ~/python.pkg -target /

      - name: Install Python dependencies and build
        run: |
          python3 --version
          pip3 install --upgrade pip wheel
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          pyinstaller weather.spec

      - name: Log files
        run: |
          ls dist
          ls dist/Weather
          mkdir Weather
          mv ./dist/Weather.app ./Weather/Weather.app
          ln -s /Applications ./Weather/Applications
          hdiutil create -srcfolder ./Weather Weather.dmg

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: Weather-Mac
          path: Weather.dmg

  build-linux:
    runs-on: ubuntu-20.04
    env:
      PYI_BUILD_MODE: "onefile"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.11.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Install requirements
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          sudo apt install python3-tk python3-pil.imagetk
      - name: Build
        run: pyinstaller weather.spec

      - name: Log files
        run: |
          ls dist
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: Weather-Linux
          path: dist/Weather

  build-windows:
    runs-on: windows-latest
    env:
      PYI_BUILD_MODE: "onefile"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.11.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Install Python dependencies and build
        run: |
          python3 --version
          pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller windows-weather.spec

      - name: Log files
        run: |
          ls dist

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: Weather-Windows
          path: dist/Weather.exe
