name: Code Formatting

on: push

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Code Formatting (App)
        run: |
          pip install ruff black isort pytest
          pip install -r requirements.txt
          black --diff .
          isort --diff .
          ruff check . # Should all be different files so we get different errors
